name: "my-website"
website:
  navbar:
    title: "Tara Pozzi"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Project Highlight: Delta Adaptation"
        file: delta.qmd
      - text: "Research"
        file: research.qmd
      - text: "CV"
        file: cv.qmd
        


project:
  type: website
  output-dir: docs
output: 
  html_document: 
   theme: darkly
   css: style.css
