+++
title = "Evaluating the impact of a climate change educational course for UC Davis"
date = 2019-04-19T00:00:00
draft = false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors = ["Tara Pozzi", "Elaina Legg", "Sarah McCullough", "Mark Lubell"]

# Publication type.
# Legend:
# 0 = Uncategorized
# 1 = Conference paper
# 2 = Journal article
# 3 = Manuscript
# 4 = Report
# 5 = Book
# 6 = Book section
publication_types = ["2"]

# Publication name and optional abbreviated version.
publication = "In *Climate change education*"
publication_short = "In *Climate change education*"

# Abstract and optional shortened version.
abstract = "Investment in transformative climate change education for graduate students can support emergent scholars to produce more ethical, effective, and relevant research to address climate inequities. We develop a transformative climate change education program called Asking Different Questions in Climate Change Science. This program is guided by a theory of change we developed based on a diverse body of literature and empirical examples, as well as qualitative data from 20 UC Davis faculty and students. Through the investigation, we found that individual characteristics such as motivations, lived experiences, and academic background, as well as contextual characteristics such as an individual’s social, cultural, and institutional environments of support, impact an individual’s experience with doing equity-focused research and practices. We argue that the integration of equity in climate change education can give graduate students the skills, knowledge, and resources to understand and respond to climate change problems more effectively." 

# Featured image thumbnail (optional)
image_preview = ""

# Is this a selected publication? (true/false)
featured = false

# Projects (optional).
#   Associate this publication with one or more of your projects.
#   Simply enter your project's filename without extension.
#   E.g. `projects = ["deep-learning"]` references `content/project/deep-learning.md`.
#   Otherwise, set `projects = []`.
projects = []

# Tags (optional).
#   Set `tags = []` for no tags, or use the form `tags = ["A Tag", "Another Tag"]` for one or more tags.
tags = []

# Links (optional).
#url_pdf = 
#url_preprint = [add prepint if i can find]
#url_code = "#"
#url_dataset = "#"
#url_project = "#"
#url_slides = "#"
#url_video = "#"
#url_poster = "#"
#url_source = "#"

# Custom links (optional).
#   Uncomment line below to enable. For multiple links, use the form `[{...}, {...}, {...}]`.
url_custom = [{name = "Link", url = "https://onlinelibrary.wiley.com/doi/full/10.1111/gove.12409"}]

# Digital Object Identifier (DOI)
# doi = "doi"

# Does this page contain LaTeX math? (true/false)
math = false

# Does this page require source code highlighting? (true/false)
highlight = false

# Featured image
# Place your image in the `static/img/` folder and reference its filename below, e.g. `image = "example.jpg"`.
[header]
image = ""
caption = ""

+++

