---
title: "CV"
---
<style type="text/css">
h1.title, h2.subtitle, h3.subtitle {
  text-align: center;
}
</style>

##### Updated August 2023

### Education

Ph.D., Ecology
Areas of Emphasis: Environmental Policy 
<span style="float:right;">**2021 – present**</span> 
Designated Emphasis: Computational Social Science
University of California Davis, Davis, CA

M.S., Biology
Areas of Emphasis: Human - Environment Systems <span style="float:right;">**2021**</span>
Thesis: Understanding the barriers and facilitators of lidar adoption for flood risk management in the Pacific Northwest, U.S.
Boise State University, Boise, ID


B.S., Civil, Environmental, and Sustainable Engineering
Areas of Emphasis: Water Resource Engineering <span style="float:right;">**2015**</span>
Thesis: Homeless Garden Project
Santa Clara Unviersity, Santa Clara, CA

***

### Publications
#### Peer-reviewed publications
**Pozzi, T.**, & Hillis, V. (2023) Social networks impact flood risk mitigation behavior: A case study of lidar adoption in the Pacific Northwest, US. *Climate Risk Management 41*. https://doi.org/10.1016/j.crm.2023.100527.

#### Manuscripts in preparation
Lubell, M., **Pozzi, T.**, Heikkila, T., and Gerlak, A. Learning through Adaptive Management in the California Delta Science Enterprise. (Policy Studies Journal) [Under Review]

**Pozzi, T.**, Legg, E., McCullough, S., & Lubell, M. Developing a Theory of Change for Integrating Equity into Climate Change Graduate Education. (Climate Change Education) [Revise and Resubmit]

**Pozzi, T.** Zufall, E., Gmoser-Dasklakis, K., & Vantaggiato, F. Nascent subsystems in polycentric governance networks: The Case of Sea Level Rise Governance in the San Francisco Bay Area (Policy Studies Journal) [Under Review]

#### Reports
**Pozzi, T.** & Lubell, M. (2023). Evolving the monitoring enterprise to meet adaptive management needs in the California Delta. Center for Environmental Policy and Behavior, UC Davis.

Lubell, M., **Pozzi, T.**, Heikkila, T., and Gerlak, A. (2022). Governing the Delta Science Enterprise: Results from a Stakeholder Survey. Center for Environmental Policy and Behavior, UC Davis. 

**Pozzi, T.** (2021). Understanding the barriers and facilitators of lidar adoption for flood risk management in the Pacific Northwest, U.S. Boise State University Theses and Dissertations. 

Lakhina, S.J., Kocher, S., Lebeda, B., Gerber-Chavez, L., Kwok, A., Stannard, D., & **Pozzi, T.** (2021). Wildfire preparedness and evacuation planning in a pandemic: Case studies from California and Colorado. CONVERGE COVID-19 Working Group for Public Health and Social Science Research. Wonder Labs, California. https://www.wonder-labs.org/uploads/6/4/2/1/6421555/wildfire-pandemic_interface_2021_report.pdf 

Ruwe, C., **Pozzi, T.**, & Miller, J. (2015). Homeless garden project. Civil, Environmental, and Sustainable Engineering Senior Theses, 34. https://scholarcommons.scu.edu/ceng_senior/34 

#### Other science and policy products
**Pozzi, T.**, & Heikkila, T. (2023) Governance of Adaptive Management Information Sheet.

**Pozzi, T.**, & Lubell, M. (2023). Uncovering the role of science governance in the Sacramento - San Joaquin Delta. Delta Breeze.

**Pozzi, T.**, Hilils, V., Glenn, N., & Enterkine, J. (2021). Knowing more, losing less through investment in High-Quality Mapping Idaho [White paper]. Boise State University. 

**Pozzi, T.**, & Hilils, V. (2021). Mapping for resilience: A story about using lidar to address Idaho’s challenges [ArcGIS Storymap]. Boise State University. https://boisestate.maps.arcgis.com/apps/Cascade/index.html?appid=63fc0118b554441589d7793e1c38ff1d 

**Pozzi, T.**, Hilils, V., Glenn, N., & Enterkine, J. (2021). Assessing and promoting the use of lidar for hazard management in Idaho via collaborative research and outreach. CTP Monthly Collaboration. 

**Pozzi, T.** (2021). LiDART. Anthroposphere. 

***

### Fellowships and awards
2023 Henry A. Jastro Research Fellowship 

2023 Public Scholars for the Future - $1,000

2022 Delta Science Fellowship, Delta Science Program and CA Sea Grant - $150,684

2022 Henry A. Jastro Research Fellowship - $3,000

2021 Weather-ready research instrument and data publication by the Natural Hazards Center - $2,500 

2020 Boise State University Graduate College Conference Presentation Award by Boise State University - $500

***

### Presentations
#### Invited talks
**Pozzi, T.** (2021) “Mapping for resilience: A storymap about using lidar to address Idaho’s Challenges”. University of Idaho GIS Day (virtual). 

#### Industry talks
**Pozzi, T.**, & Lubell, M. (2023) A social science perspective on the monitoring enterprise (virtual).

Lubell, M., & **Pozzi, T.** (2023) “Summary of Science Governance Research”. Delta Stewardship Council Meeting (in-person). 

**Pozzi, T.** (2021) “ State of lidar adoption in Idaho”. Elevation Technical Working Group Monthly Meeting (virtual). 

**Pozzi, T.** (2020) “Current State of Lidar in Flood Risk Management in Idaho”. Webinar (virtual).

#### Campus talks
**Pozzi, T.** (2020) “Lidar uptake in Pacific Northwest”. 3-Minute Thesis Competition Finals (in-person). 

**Pozzi, T.** (2020) “Lidar uptake in Pacific Northwest”. Biological Science Graduate Student Proposal Showcase (in-person). 

#### Conference activity
**Pozzi, T.** & Zufall, E. (2023) “Nascent subsystems in polycentric governance networks: The Case of Sea Level Rise Governance in the San Francisco Bay Area”. Conference on Policy Process Research (in person). 

**Pozzi, T.** (2020) “Technology Adoption in Flood Risk Management: A Case Study in Idaho”. Natural Hazards Workshop (virtual).
 
**Pozzi, T.** (2020) “Technology Adoption in Flood Risk Management: A Case Study in Idaho”. International Symposium on Society and Resource Management (virtual).

***

### Research
Lead researcher. Mixed-methods study on the climate adaptation governance network of the Sacramento – San Joaquin Delta, under the direction of Dr. Mark Lubell and Lindsay Correa. Funded by CA Sea Grant and the Delta Science Program. <span style="float:right;">**2022 – present**</span> 

Research Assistant. Data analysis for long-term monitoring needs assessment for the Collaborative Adaptive Management Team of the San Joaquin-Sacramento Delta under the direction of Dr. Mark Lubell, Dr. Louise Conrad, and Bruce DiGennaro. Funded by the Delta Science Program.<span style="float:right;">**2022 – present**</span> 

Research assistant. Design and implement study for measuring the factors that influence students to conduct research with awareness of diversity, equity, and inclusion in climate change context, under direction of Dr. Mark Lubell and Dr. Sarah McCullough. Funded by Feminist Research Institute. <span style="float:right;">**2022 – present**</span> 

Research assistant. Conduct survey data analysis and report writing for the Delta science enterprise, under direction of Dr. Mark Lubell. Funded by Delta Stewardship Council. <span style="float:right;">**2021 - 2022**</span> 

Research assistant. Support academic and policy research for wildfire applications in the American west, under direction of Dr. Shefali Lakhina. Funded by Wonder Labs. <span style="float:right;">**2021**</span> 

Lead researcher. Mixed-methods empirical study on lidar adoption for flood risk management in the Pacific Northwest. Social-ecological science to understand relative effect of individual and collective factors of decision-making, under direction of Dr. Vicken Hillis. Funded by the Department of Homeland Security. <span style="float:right;">**2019-2021**</span> 

***

### Teaching and Mentoring
#### Teaching
Instructor. R-Davis, UC Davis <span style="float:right;">**2022 – present**</span> 

Readership. Public Land Governance, UC Davis. <span style="float:right;">**2021**</span> 

#### Mentoring
Emily Denio (Undergraduate intern, BS Environmental Science and Policy 2025).<span style="float:right;">**2023 – present**</span> 

Eden Winniford (Research assistant, BS Environmental Science and Policy 2023).<span style="float:right;">**2023 – present**</span> 

Elaina Legg (Research assistant, BS Communication and Psychology 2023). <span style="float:right;">**2022 – 2023**</span> 

Graduate student mentor. Vertically Integrated Project, Boise State University. <span style="float:right;">**2021**</span> 

Field instructor mentor and trainer. blueFire Wilderness Therapy, Idaho.<span style="float:right;">**2018-2019**</span> 

***

### Service
Facilitator. Adaptive Management Forum Day 2. <span style="float:right;">**2023**</span> 

Advisory Board member. Adaptive Management Forum. <span style="float:right;">**2023**</span> 

Davis R Users’ Group coordinator at UC Davis.<span style="float:right;">**2022 - Present**</span> 

Co-chair. Ecology Graduate Student Association at UC Davis. <span style="float:right;">**2022 - 2023**</span> 

Facilitator. Ecology Graduate Group Orientation. <span style="float:right;">**2022**</span> 

Facilitator. Advancing Interdisciplinary Research Workshop.<span style="float:right;">**2022**</span> 

Member and facilitator for Ecology Symposium.
Ecology Graduate Student Association at UC Davis.<span style="float:right;">**2021**</span> 

Editor and contributor for student paper, Brickyard. Ecology Graduate Student Association at UC Davis.
<span style="float:right;">**2021**</span> 

Member and facilitator. Ecological Research Association Diversity, Equity, and Inclusion Task Force. <span style="float:right;">**2021**</span> 

Organizer. GRFP Review Group. <span style="float:right;">**2020**</span> 

***

### Certificates
Institutional Review Board Certification in Social and Behavioral Responsible Conduct of Research <span style="float:right;">**2021**</span> 

CONVERGE Disaster Training Modules, Natural Hazards Center: Social Vulnerability and Disasters, Disaster Mental Health. <span style="float:right;">**2021**</span> 

***

### Affiliations
Member, American Society of Adaptation Professionals <span style="float:right;">**2022**</span> 

Member, International Association of Society and Natural Resources <span style="float:right;">**2020**</span> 



