---
title: "Research"
---

My research investigates how to build capacity for effective and equitable climate adaptation solutions. As a mixed-methods social scientist, I conduct studies that use both qualitative approaches such as interviews and focus groups, and quantitative methodologies such as social network analysis and Bayesian statistics. 

***

### Ongoing Projects 

#### Collaborative governance of climate adaptation in the Delta
As the main source of water supply for two-thirds of California, a unique biodiversity hot spot, and home to many communities, the Sacramento - San Joaquin Delta is known as the *heart* of California. Impacted by flooding, water shortage, extreme heat, and wildfire, my research explores how human communities in the Delta are adapting to climate vulnerabilities and how they can leverage and build their partnerships to build social, technical, and financial capital. The research leverages both interview and survey data. The outputs of this project will include a governance challenges report, a network map of organizations and their partnerships, and a recorded presentation of the results. 

**Interested in learning more? Reach out to me directly**


#### Evaluating the impact of a climate change educational course for UC Davis
Investment in transformative climate change education for graduate students can support emergent scholars and practitioners to produce more ethical, effective, and relevant research to address climate inequities. We developed a transformative climate change education program called Asking Different Questions in Climate Change Science that focuses on equity. This program is guided by a theory of change we developed based on a diverse body of literature and empirical examples, as well as qualitative data from 20 UC Davis faculty and students. Through the investigation, we found that individual characteristics such as motivations, lived experiences, and academic background, as well as contextual characteristics such as an individual’s social, cultural, and institutional environments of support, impact an individual’s experience with doing equity-focused research and practices. We argue that the integration of equity in climate change education can give graduate students the skills, knowledge, and resources to understand and respond to climate change problems more effectively.

Materials: 
**Pozzi, T.**, Legg, E., McCullough, S., & Lubell, M. Developing a Theory of Change for Integrating Equity into Climate Change Graduate Education. (Climate Change Education) [Revise and Resubmit]

#### Science Enterprise and Adaptive management 
Science is critical for learning and adaptation of policy and governance systems. Increasingly, science is produced in the context of a science enterprise: a complex, polycentric institutional arrangement featuring multiple science forums and actors. The characteristics of these polycentric systems likely matter for whether and to what extent science supports policy-relevant learning. Limited research, however, has examined how science enterprises function as polycentric systems and how they can be governed to support learning. Using a survey of actors involved in the science enterprise of the California Delta, we integrate the collective learning framework and ecology of games framework to analyze individual and forum-level drivers of learning. The results suggest that social drivers such as leadership, trust, and engagement that are most highly correlated with perceived learning. While science enterprise actors often perceive administrative and financial resource limitations, those constraints are less important for learning than social drivers. 

Materials: 
**Pozzi, T.** & Lubell, M. (2023). Evolving the monitoring enterprise to meet adaptive management needs in the California Delta. Center for Environmental Policy and Behavior, UC Davis.

Lubell, M., **Pozzi, T.**, Heikkila, T., and Gerlak, A. (2022). Governing the Delta Science Enterprise: Results from a Stakeholder Survey. Center for Environmental Policy and Behavior, UC Davis. 

Lubell, M., **Pozzi, T.**, Heikkila, T., and Gerlak, A. Learning through Adaptive Management in the California Delta Science Enterprise. (Policy Studies Journal) 
