---
title: "Research"
website: 
  navbar: 
    background: darkolivegreen
---

**Research Themes**

Science Governance

Social Networks

Climate Justice

#### Environmental Justice Networks

Abstract: Environmental justice (EJ) groups rely on informal collaborative networks to amplify their voices and mobilize resources for addressing disproportionate environmental burdens. These networks, shaped by relationships between EJ groups and their partners, shape the effectiveness of an EJ movement to influence environmental policy and decision-making. Drawing from social movement literature, we examine how resource exchange motivations and boundary definition drivers affect EJ groups' partner preferences among EJ groups in the Sacramento-San Joaquin Delta region of California. Using network data from 21 EJ groups gathered through interviews, we implement a cross-classified generalized linear mixed model to estimate the effects of organizational attributes and collaborative participation, EJ commitment and issue focus areas, and geography on the likelihood of collaboration ties in egocentric social networks. Overall, we find evidence of both strong and weak ties occurring in partner selection. EJ groups seek partners with shared issue focus areas as well as broker organizations who participate in collaborative initiatives. Geographic proximity also plays a key role with groups preferring local partners mostly, but also finding value in partners that operate at larger geographic scales. Overall, the study provides evidence that EJ groups strategically structure personal networks to leverage resources, address issues of concern, and ultimately strengthen the EJ movement.

Outputs:

**Pozzi, T.**, Lubell, M., and Rudnick, J. (2024) Leveraging Parnterships in the Environmental Justice Movement: A Case Study in the California Delta. \[In Prep\]

------------------------------------------------------------------------

#### Learning in the Delta Science Enterprise

Abstract: Science is critical for learning and adaptation of policy and governance systems. Increasingly, science is produced in the context of a science enterprise: a complex, polycentric institutional arrangement featuring multiple science forums and actors. The characteristics of these polycentric systems likely matter for whether and to what extent science supports policy-relevant learning. Limited research, however, has examined how science enterprises function as polycentric systems and how they can be governed to support learning. Using a survey of actors involved in the science enterprise of the California Delta, we integrate the collective learning framework and ecology of games framework to analyze individual and forum-level drivers of learning. The results suggest that social drivers such as leadership, trust, and engagement that are most highly correlated with perceived learning. While science enterprise actors often perceive administrative and financial resource limitations, those constraints are less important for learning than social drivers.

Outputs:

Lubell, M., **Pozzi, T.**, Heikkila, T., and Gerlak, A. (2024). Learning through Adaptive Management in the California Delta Science Enterprise. (Policy Studies Journal) \[Conditionally Accepted\]

**Pozzi, T.**, & Lubell, M. (2023). Uncovering the role of science governance in the Sacramento - San Joaquin Delta. Delta Breeze.

Lubell, M., **Pozzi, T.**, Heikkila, T., and Gerlak, A. (2022). Governing the Delta Science Enterprise: Results from a Stakeholder Survey. Center for Environmental Policy and Behavior, UC Davis.

Media:

[Delta Stewardship Council Social Science Integration by Maven's Notebook](https://mavensnotebook.com/2023/03/16/delta-stewardship-council-integrating-social-sciences-in-the-delta/)

------------------------------------------------------------------------

#### Evaluating the impact of a climate change educational course for UC Davis

Abstract: Investment in transformative climate change education for graduate students can support emergent scholars and practitioners to produce more ethical, effective, and relevant research to address climate inequities. We developed a transformative climate change education program called Asking Different Questions in Climate Change Science that focuses on equity. This program is guided by a theory of change we developed based on a diverse body of literature and empirical examples, as well as qualitative data from 20 UC Davis faculty and students. Through the investigation, we found that individual characteristics such as motivations, lived experiences, and academic background, as well as contextual characteristics such as an individual's social, cultural, and institutional environments of support, impact an individual's experience with doing equity-focused research and practices. We argue that the integration of equity in climate change education can give graduate students the skills, knowledge, and resources to understand and respond to climate change problems more effectively.

Outputs:

**Pozzi, T.**, Legg, E., McCullough, S., & Lubell, M. Developing a Theory of Change for Integrating Equity into Climate Change Graduate Education. (Environmental Education Research) \[Revise and Resubmit\]
