name: rsync-to-server
on:
  push:
    branches:
      - main

jobs:
  rsync-to-remote-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: zip and backup current deployment on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          zip -r backup/backup.zip public_html/

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo $(pwd)
        echo "$KEY" > private.key
        sudo chmod 600 private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH: ${{ github.workspace }}/private.key

    - name: deploy with rsync
      run: rsync -avz "ssh -i $SSH_KEY_PATH" _site ${{ secrets.USERNAME }}@${{ secrets.HOST }}:REPOSITORY